version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ../.env
  
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    entrypoint: redis-server --appendonly yes
  
  web:
    build: ../.
    restart: always
    volumes:
      - static_value:/app/api_spot/static/
      - media_value:/app/api_spot/media
    depends_on:
      - db
    env_file:
      - ../.env
  
    
  celery:
    build: ../
    command: celery -A api_spot worker --loglevel=info
    volumes:
      - app:/app
    env_file:
      - ../.env
    depends_on:
      - web
      - redis
  
  flower:
    image: mher/flower
    restart: always
    expose:
      - 5555
    environment:
      - CELERY_BROKER_URL=redis://redis:6379
      - FLOWER_PORT=5555
      - FLOWER_URL_PREFIX=/flower
    depends_on:
      - web
      - redis
      - celery
  
  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    links:
      - web
    depends_on:
      - web
      - flower


volumes:
  static_value:
  media_value:
  postgres_data:
  app: